language: python
jobs:
  include:
  - name: macOS 10.13
    os: osx
    osx_image: xcode9.4
    language: shell
  - name:
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.0
    - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
- pip3 install --upgrade pip
- pip3 install -r requirements.txt
script:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyinstaller YoYoMachines-Firmware-Uploader.spec && zip -r dist/YoYoMachines-Firmware-Uploader.app.zip dist/Yo-Yo\ Machines\ Firmware\ Uploader.app ; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then pyinstaller -F -w -n Yo-Yo\ Machines\ Firmware\ Uploader --icon=images/icon.ico esptool-python-gui.py && tar.exe -a -c -f dist/YoYoMachines-Firmware-Uploader.exe.zip dist/Yo-Yo\ Machines\ Firmware\ Uploader.exe ; fi
deploy:
  provider: releases
  api_key:
    secure: mAGMwjR7aYpZrSOlKEcoscIQ1uLvWRB/biSoUN0Kd2HjBfwkJyRcVZhJso2yK/NurVsgXSwN5dVZixsOJsA42txsnEMSAllepBjeaoy6gnWQpoqmz2MIzw9cloyicw113RJM8WrWyoQ68OKjlx1u+uyHKbmNC0U1vflXDgtDZDflDFXtZV6htrihFIBd/MQ1lBMDg7mPy2bmDUmatWYz5/LmEMLC5a/Og33+/xKvx+nJlvYZl36rHnPf6bsnlSFUIrVHBcCNPbVZdHwd6JyC1RMSIiLolprUtNUyJGfKW62iMf8xRtzPWb0rEmcaLB8ZjFtJF2HRoRpUJwmgUQH7S0GWyAYARlmNWGW4hlmlonX5FKK7N8ZbqI0hOXBKVaxRXuWl5HK978brKnTh5Tcw31TTtMjnI+fADCLgPq9usVNhAeCZGx7vaJ0dUTU1EzTRTnPZ/WK5VjyA1urRSzD3C5znc/29NBpK1nIKyZ/FBuEpDSgmbBI7sKJG82QNjUcdH8/BDRD4TRzt6mmSU4OF9vvV8/dcJP00iIBFb4cMw5gX5qFTCpenphAx4rXp2vQgOT02WlOvOewSPFQUn3NwSJGqowh5bnlDln12GvPqEHmC17huRznyGXM2Mh0oh5R4GMmOJXaAwyHAix9Rw3LQjg0WXwp1NlyVBZLz3TivRqg=
  file:
    - dist/YoYoMachines-Firmware-Uploader.app.zip
    - dist/YoYoMachines-Firmware-Uploader.exe.zip
  on:
    tags: true
  skip_cleanup: 'true'
  draft: 'true'
