language: python
jobs:
  include:
  - name: macOS 10.13
    os: osx
    osx_image: xcode9.4
    language: shell
install: pip3 install --upgrade pip
script: pip3 install -r requirements.txt && pyinstaller YoYoMachines-Firmware-Uploader.spec
deploy:
  provider: releases
  api_key:
    secure: wgiiPyINY2fdTSWLwK+EoTUIEy1EYVqG7G/R8G4/NptgbMr4NNfzy7M8M+iTH7boGUX+/MUWFGiWK8OsL5YKHkzReHlgpSeaKfMnkUQnffuZXXbWMLQTiM+jxCg1ssuzrac89ZCIg3Y3NBJwtgrOJDEKE6z7G40YYp56eQ5Kymxn8hBk8QSo0H3VeohhmxOEra8XFStW4aNLb+F9aLe333ytCCAV92WWFzwnyCo2SYvtUy2Bqf9QoIMQP/EFMio2hQWoUPT5IiJdbZrqAP+XQZCWru6YfUK+nWQ6WjQCKw4xsv6llm54iCk5HrCi0JEll5RcArjSFkhn2sPULD9F0bAWiFs4MIuAkjM/ul2u16pUlxLQ4S5wp4l6JjD+pzJqT/iak47ZLAyUmZSxDRUOnb46sK765aTyGJy3QsznnUwhNI9qhcA6y19alw/NZSgUyZKxy1OPDkem0x0vNPrQejIRvuj5JEESMHLHlV60NFtEi9vVZsrHYMm1lD+1VePaf7wlhIrleOAPQK2BzvXKcGGriX8/ePHTiqsh6mE+YzC38PwBky1wtvTDRuJxmCDxaCqtEUD7x0n/r0asbdCspVxkmaU6blLNwxE/T6ZYlprIf+vVR9CL9hcqakXttURbDZ+fZ5HnwDKrGa7+x9hwQxRZUoR67hN05EDuF9OETto=
  file: dist/*
  on:
    repo: mikevanis/esptool-python-gui
  skip_cleanup: 'true'
