name: Build Workflow

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller -F -w -n YoYoMachines-Firmware-Uploader esptool-python-gui.py
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: dist/YoYoMachines-Firmware-Uploader.exe

  build-windows-x86:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.9'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller -F -w -n YoYoMachines-Firmware-Uploader esptool-python-gui.py
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-x86
          path: dist/YoYoMachines-Firmware-Uploader.exe

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.8'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller YoYoMachines-Firmware-Uploader.spec
      - name: Set permissions
        run: chmod 755 dist/
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: dist/
      - uses: actions/upload-artifact@v2
        with:
          name: macOS-debug
          path: dist/
