name: Build Workflow

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller.__main__ -F -w -n IRS-Firmware-Uploader esptool-python-gui.py
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: dist/IRS-Firmware-Uploader.exe

  build-windows-x86:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller.__main__ -F -w -n IRS-Firmware-Uploader esptool-python-gui.py
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-x86
          path: dist/IRS-FirmwareUploader.exe

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller.__main__ -F -w -n IRS-Firmware-Uploader esptool-python-gui.py
      - name: See dist directory
        run: ls dist
      - name: Move app
        run: |
          mv dist/ESPHome-Flasher.app dist/ESPHome-Flasher-dev-macOS.app
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: dist/
